FROM ghcr.io/graalvm/graalvm-community:17 as build

RUN microdnf update
RUN microdnf upgrade -y
RUN microdnf install maven

WORKDIR /opt/build

COPY src src
COPY pom.xml pom.xml
RUN mvn dependency:go-offline

COPY Dockerfile_linux_entrypoint.sh entrypoint.sh
RUN chmod +x /opt/build/entrypoint.sh

RUN mkdir -p /opt/output

ENTRYPOINT [ "/opt/build/entrypoint.sh" ]