info:
  name: '@project.artifactId@'
  version: '@project.version@'
spring:
  main:
    web-application-type: none
    banner-mode: off
    allow-bean-definition-overriding: true
logging:
  level:
    root: error