pipeline {
    environment {
        MAILTO_ON_FAIL     = "n.zoltan18@gmail.com"

        NAME               = "cps-npmrcm-manager"
        ROOT               = "."

        JDK_TOOL           = "graalvm-17"
        MVN_TOOL           = "maven-3.9.4"
    }

    agent {
        label 'linux_arm64'
    }

    triggers {
        pollSCM "H/15 * * * *"
    }

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage ('preparation') {
            steps {
                deleteDir()
                checkout scm
            }
        }

        stage ('mvn clean package') {
            steps {
                withMaven(maven: env.MVN_TOOL, jdk: env.JDK_TOOL) {
                    sh "mvn -f ${env.ROOT}/pom.xml clean package"
                }
            }
        }
    }

    post {
        failure {
            emailext(to: "${env.MAILTO_ON_FAIL}", subject: '$DEFAULT_SUBJECT', body: '$DEFAULT_CONTENT')
        }
    }
}