def version
def executableName

pipeline {
    environment {
        MAILTO_ON_FAIL     = "n.zoltan18@gmail.com"

        NAME               = "cps-npmrc-manager"
        ROOT               = "."
        BUILD_ARCH         = "linux_arm64"

        NEXUS_URL          = "https://build.cp-sys.hu/nexus/repository/executable-releases"
        NEXUS_CREDENTIALS  = "pigeon-nexus"

        JDK_TOOL           = "graalvm-17"
        MVN_TOOL           = "maven-3.9.4"
    }

    agent {
        label 'linux_arm64'
    }

    triggers {
        upstream 'cps-npmrc-manager/ci/java'
    }

    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage ('preparation') {
            steps {
                deleteDir()
                checkout scm
                script {
                    def pom = readMavenPom(file: "${env.ROOT}/pom.xml")

                    String snapshotVersion = pom.getVersion()
                    version = snapshotVersion.replaceFirst("-SNAPSHOT|-RC|-RELEASE", "")

                    def properties = pom.getProperties()
                    executableName = properties.getProperty("executable.name")
                }
            }
        }

        stage ('maven build') {
            steps {
                withMaven(maven: env.MVN_TOOL, jdk: env.JDK_TOOL, options: [artifactsPublisher(disabled: true)]) {
                    sh "mvn clean package -Pnative -f ${env.ROOT}/pom.xml"
                }
            }
        }

        stage ('publish executable') {
            steps {
                withCredentials([usernameColonPassword(credentialsId: "${env.NEXUS_CREDENTIALS}", variable: 'NEXUS_USERPASS')]) {
                    script {
                        def tarName = "${env.NAME}_${env.BUILD_ARCH}_${version}.tar.gz"
                        tar(archive: true, compress: true, defaultExcludes: false, dir: "${env.ROOT}/target", exclude: '', file: tarName, glob: executableName, overwrite: true)
                        sh "curl -v" + ' --user $NEXUS_USERPASS' + " --upload-file ./$tarName ${env.NEXUS_URL}/${env.NAME}/$version/${env.BUILD_ARCH}/$tarName"
                    }
                }
            }
        }
    }

    post {
        failure {
            emailext(to: "${env.MAILTO_ON_FAIL}", subject: '$DEFAULT_SUBJECT', body: '$DEFAULT_CONTENT')
        }
    }
}
